CateringProject/Models/OrderModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CateringProject.Models
{
    public class OrderModel
    {
        public int UserId { get; set; }
        [Required(ErrorMessage ="Required")]
        [Display(Name ="User Name")]
        public string UserName { get; set; }
        [DataType(DataType.Date)]
        [Display(Name ="Date&Time")]
        [Required(ErrorMessage = "Required")]
        public DateTime CreatedDate { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name ="Phone Number")]
        public string PhoneNo { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name ="Email ID")]
        public string EmailId { get; set; }
    }
}

CateringProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CateringProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CateringProject/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CateringProject.DAL;
using CateringProject.Models;

namespace CateringProject.Controllers
{
    public class HomePageController : Controller
    {
        CateringDB cater=new CateringDB();
        // GET: HomePage
        public ActionResult Index()
        {
            return View(cater.GetUsers());
        }
        public ActionResult Menu()
        {
            return View();
        }

        // GET: HomePage/Details/5
        public ActionResult Details(int id)
        {
            return View(cater.GetUsers().Find(pmodel => pmodel.UserId == id));
        }

        // GET: HomePage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomePage/Create
        [HttpPost]
        public ActionResult Create(OrderModel omodel)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    cater.AddUser(omodel);
                    return RedirectToAction("ThankYou");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult ThankYou()
        {
            return View();
        }
        // GET: HomePage/Edit/5
        public ActionResult Edit(int id)
        {
            return View(cater.GetUsers().Find(pmodel => pmodel.UserId == id));
        }

        // POST: HomePage/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, OrderModel omodel)
        {
            try
            {
                // TODO: Add update logic here
                cater.UpdateUser(omodel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HomePage/Delete/5
        public ActionResult Delete(int id)
        {
            return View(cater.GetUsers().Find(pmodel => pmodel.UserId == id));
        }

        // POST: HomePage/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, OrderModel model)
        {
            try
            {
                // TODO: Add delete logic here
                cater.DeleteUser(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CateringProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

CateringProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

CateringProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

CateringProject/Views/HomePage/Create.cshtml
@model CateringProject.Models.OrderModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/CateringLayout.cshtml";
}

<link href="~/Content/MainStyle.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    <div class="bg">
        <img src="~/images/chefff.png" class="img5" />
        <div class="div1">
            <center>
                <img src="~/images/orderf.png" class="img2" />
                <p class="p6">Book Our Services</p>
            </center>
            <hr />
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "label1" })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "validator" })
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "label3" })
            @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "validator" })
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "textbox2" } })
            @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "textbox1" } })
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "label2" })
            @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "validator" })
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "label4" })
            @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "validator" })
            @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "textbox2" } })
            @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "textbox1" } })
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Order Now" class="btn" />
                </div>
            </div>
        </div>
    </div>
    <div class="div2">
        <div class="div4">
            <div class="div6">
                <img src="~/images/cupf.jpg" class="img1" />
                <p class="p4">Good Rest</p>
                <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>
            <div class="div6">
                <img src="~/images/food.png" class="img1" />
                <p class="p4">Best Cuisine</p>
                <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>
        </div>
        <div class="div3">
            <p class="p1">Best One</p>
            <p class="p2">Our Services</p>
            <hr class="hr1" />
            <p>
                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                The point of using lorem ipsum is that it has a more-or-less normal dustribution of letters or opposed to using "content here content here"
                making it look like readable English.
            </p>
            <p class="p3">Read More</p>
        </div>
        <div class="div5">
            <div class="div7">
                <img src="~/images/timef.jpg" class="img1" />
                <p class="p4">24/7</p>
                <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>
            <div class="div7">
                <img src="~/images/platef.jpg" class="img1" />
                <p class="p4">Special Event Catering</p>
                <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
            </div>
        </div>
    </div>
}

CateringProject/Views/HomePage/Delete.cshtml
@model CateringProject.Models.OrderModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CateringProject/Views/HomePage/Details.cshtml
@model CateringProject.Models.OrderModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OrderModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CateringProject/Views/HomePage/Edit.cshtml
@model CateringProject.Models.OrderModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrderModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CateringProject/Views/HomePage/Index.cshtml
@model IEnumerable<CateringProject.Models.OrderModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.UserId }) |
            @Html.ActionLink("Details", "Details", new { id = item.UserId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.UserId  })
        </td>
    </tr>
}

</table>

CateringProject/Views/HomePage/Menu.cshtml
@model CateringProject.Models.OrderModel

@{
    ViewBag.Title = "Menu";
    Layout = "~/Views/Shared/CateringLayout.cshtml";
}


<link href="~/Content/MenuStyle.css" rel="stylesheet" />
    @using (Html.BeginForm())
    {
        <div class="bg">
            <img src="~/images/chefff.png" class="img5" />
            <div class="div1">
                <center>
                    <img src="~/images/orderf.png" class="img2" />
                    <p class="p6">Book Our Services</p>
                </center>
                <hr />
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "label1" })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "validator" })
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "label3" })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "validator" })
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "textbox2" } })
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "textbox1" } })
                @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "label2" })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "validator" })
                @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "label4" })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "validator" })
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "textbox2" } })
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "textbox1" } })
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Order Now" class="btn" />
                    </div>
                </div>
            </div>
        </div>
        <div class="div2">
            <div class="div4">
                <div class="div6">
                    <img src="~/images/cupf.jpg" class="img1" />
                    <p class="p4">Good Rest</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
                <div class="div6">
                    <img src="~/images/food.png" class="img1" />
                    <p class="p4">Best Cuisine</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
            </div>
            <div class="div3">
                <p class="p1">Best One</p>
                <p class="p2">Our Services</p>
                <hr class="hr1" />
                <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                    The point of using lorem ipsum is that it has a more-or-less normal dustribution of letters or opposed to using "content here content here"
                    making it look like readable English.
                </p>
                <p class="p3">Read More</p>
            </div>
            <div class="div5">
                <div class="div7">
                    <img src="~/images/timef.jpg" class="img1" />
                    <p class="p4">24/7</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
                <div class="div7">
                    <img src="~/images/platef.jpg" class="img1" />
                    <p class="p4">Special Event Catering</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
            </div>
        </div>
    }

CateringProject/Views/HomePage/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
    Layout = "~/Views/Shared/CateringLayout.cshtml";
}
<link href="~/Content/ThankYou.css" rel="stylesheet" />
<div class="div1">
    <h2>Thank you for choosing us</h2>
    <h3>Our team will contact you soon.</h3>
</div>

CateringProject/Views/Shared/CateringLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/CateringLayout.css" rel="stylesheet" />
</head>
<body>
    <div class="menudiv">
        <img src="~/images/logof.png" class="img3" />
        <ul>
            <li>@Html.ActionLink("Home", "Create", "HomePage", new { area = "" }, new { @class = "link1" })</li>
            <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "link1" })</li>
            <li>@Html.ActionLink("Orders", "Index", "HomePage", new { area = "" }, new { @class = "link1" })</li>
            <li>Services</li>
            <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "link1" })</li>
        </ul>
    </div>
    <div class="bodydiv">
        @RenderBody()
        <footer class="footer">
            <hr />
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>

CateringProject/Views/Shared/Demo.cshtml
@model CateringProject.Models.OrderModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/CreateStyle.css" rel="stylesheet" />
    <title>Index</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        <div class="bg">
            <img src="~/images/logof.png" class="img3" />
            <ul>
                <li>@Html.ActionLink("Home", "Create", "HomePage", new { area = "" }, new { @class = "link1" })</li>
                <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "link1" })</li>
                <li>Menu</li>
                <li>Services</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "link1" })</li>
            </ul>
            <img src="~/images/chefff.png" class="img5" />
            <div class="div1">
                <center>
                    <img src="~/images/orderf.png" class="img2" />
                    <p class="p6">Book Our Services</p>
                </center>
                <hr />
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "label1" })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "validator" })
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "label3" })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "validator" })
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "textbox2" } })
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "textbox1" } })
                @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "label2" })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "validator" })
                @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "label4" })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "validator" })
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "textbox2" } })
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "textbox1" } })
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Order Now" class="btn" />
                    </div>
                </div>
            </div>
        </div>
        <div class="div2">
            <div class="div4">
                <div class="div6">
                    <img src="~/images/cupf.jpg" class="img1" />
                    <p class="p4">Good Rest</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
                <div class="div6">
                    <img src="~/images/food.png" class="img1" />
                    <p class="p4">Best Cuisine</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
            </div>
            <div class="div3">
                <p class="p1">Best One</p>
                <p class="p2">Our Services</p>
                <hr class="hr1" />
                <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
                    The point of using lorem ipsum is that it has a more-or-less normal dustribution of letters or opposed to using "content here content here"
                    making it look like readable English.
                </p>
                <p class="p3">Read More</p>
            </div>
            <div class="div5">
                <div class="div7">
                    <img src="~/images/timef.jpg" class="img1" />
                    <p class="p4">24/7</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
                <div class="div7">
                    <img src="~/images/platef.jpg" class="img1" />
                    <p class="p4">Special Event Catering</p>
                    <p class="p5">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                </div>
            </div>
        </div>
    }
</body>
</html>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CateringProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>